apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  # Base64 encoded secrets
  aws_access_key: {{ .Values.secrets.awsAccessKey | b64enc | quote }}
  aws_secret_key: {{ .Values.secrets.awsSecretKey | b64enc | quote }}
