apiVersion: v1
kind: Pod
metadata:
  name: jenkins-test
spec:
  containers:
  - name: code-builder
    image: 791532114280.dkr.ecr.us-east-1.amazonaws.com/mstr-build-agent:oi-pi-image-1.3
    command:
    - cat
    tty: true
  - name: image-builder
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      configMap:
        name: docker-config
